### ISSUE TITLE
huffle pox trends by zcta: hospitalizations vs deaths (2010 vs 2015)

### ISSUE THREAD

**Issue by her43** [Drexel-UHC/duckdb-dbt-template#11]

**Comment by ran-codes** [comment]
@her43 can you detail the columns you want in the final table?

**Comment by her43** [comment]
> @her43 can you detail the columns you want in the final table?
> 
> I am going to assume
> 
> Columns: ZCTA, YEAR, CountHufpoxHospitalization, CountHufpoxDeath Rows: One record per ZCTA Year
> 
> ## Hufflepox codes
> "D2463" "D2511"

yeah that looks good to me! Did you make up fake ICD codes for this?

**Comment by ran-codes** [comment]
yup everyfake. even zctas... (in the perferct world zcta and zip would be the same thing and everythignw ould be 1:1.... this is that world 😄 )

**Comment by ran-codes** [comment]
great done! as per @her43
