### ISSUE TITLE
ModuleNotFoundError: No module named 'duckdb': Steve Melly

### ISSUE THREAD

**Issue by sjmelly** [Drexel-UHC/duckdb-dbt-template#4]
![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/16820816/2a35d990-b9ea-4cbb-b9c2-bb3591e7a9a1)

**Comment by sjmelly** [comment]
![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/16820816/1c9fdeee-ded7-4e93-8d97-5bae04111d07)

**Comment by ran-codes** [comment]
Steve we found the problem and have fixed it for Jess in #6. The setup instructions have been updated accordingly.

Can you try the following:

- [ ] delete your /hello/ folder
- [ ] pull from origin ([instructions on how to pull](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch-in-github-desktop))
- [ ] then please start from [step 1.7 Setup Local Python Environment](https://drexel-uhc.github.io/analytics-corner/pages/manuals/dbt/get-started-install.html#setup-local-python-environment)

Please let me know how it works for you.

**Comment by sjmelly** [comment]
I'm getting this error when I click on Open in Visual Studio
![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/16820816/b0e61b59-ffcd-411f-9ac8-13fe96993f8d)

**Comment by ran-codes** [comment]
steve, can you create a new branch called `steve-melly-dbt` and push your code. so I can try to reproduce your error. 

Some steps i think you will need to do:
- [ ] discard all your changes on main branch - [instructions on discarding changins](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project-in-github-desktop#discarding-changes)
- [ ] Create a new branch  called `steve-m-dbt` - [instructions on creating a branch](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project-in-github-desktop#discarding-changes)
- [ ] publish your branch to origin - [instructions on how to publish branch to origin](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project-in-github-desktop#discarding-changes)

**Comment by sjmelly** [comment]
I think I created the new branch

**Comment by ran-codes** [comment]
yup i see it great job!! (congrats on your first branch 🍰 )

## **Two things to check now.**

- [ ] Navigate to your `./venv/pyvenv.cfg` and take asnip as shown in snip 1 below
- [ ] Navigate to your local libraries `.venv/Lib` folder and check that dbt is installed (one of folders is named `dbt`) - as shown in snip 2. Please take a snip of your `.venv/Lib` folder as shown in snip 2.

[Instructions on how to attach snips/images](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)

### Snip 1 (check python configuration)

![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/45013044/afc1fd2c-819a-465a-beb8-3fcd8599a3e9)


### Snip 2 (Check DBT installation)

![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/45013044/cc6e95f4-eceb-414b-8e21-ffd6eb6241da)

**Comment by sjmelly** [comment]
It appears that DBT is not installed. I tried uninstalling it and installing again and got this message
![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/16820816/967b7d5b-a920-44a5-8636-1af4ffe8fcfb)

![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/16820816/52bd60e4-42d2-419d-8f13-cbf6360a2411)


![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/16820816/0e963683-9227-43d7-a106-8ae097df9886)

**Comment by sjmelly** [comment]
That worked. Thanks!
![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/16820816/5cc8ac9c-cb04-45a5-bcda-fdfa029397ea)
