### ISSUE TITLE
Error when running step 1.7

### ISSUE THREAD

**Issue by Nat325** [Drexel-UHC/duckdb-dbt-template#5]
![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/116823103/18f23a5f-39ed-4f79-8f33-b69ac32e921a)

Here is the error I get when running step 1.7. 

I went to the site specified to get Rust and when trying to install Rust, I get the following errors.
![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/116823103/32b67460-8bcb-41d3-a153-60a2c2fb4a5f)

**Comment by Nat325** [comment]
![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/116823103/5782fe98-335d-4dca-b632-7fcbb864ac2a)
error when running dbt compile

**Comment by ran-codes** [comment]
quick q. are you mac or windows?

**Comment by Nat325** [comment]
I'm on windows 10!

**Comment by ran-codes** [comment]
Thanks! Can you try the following: 

Can you create a new branch called `nat-dbt` and push your code. so I can try to reproduce your error. 

Some steps you will need to do:
- [ ] discard all your changes on main branch - [instructions on discarding changes](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project-in-github-desktop#discarding-changes)
- [ ] Pull from origin - [instructions on how to pull](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch-in-github-desktop#pulling-to-your-local-branch-from-the-remote)
- [ ] Create a new branch  called `natalie-dbt` - [instructions on creating a branch](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project-in-github-desktop#discarding-changes)
- [ ] publish your branch to origin - [instructions on how to publish branch to origin](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/committing-and-reviewing-changes-to-your-project-in-github-desktop#discarding-changes))
- [ ] Navigate to your `./.venv/pyvenv.cfg` and take asnip as shown in snip 1 below
- [ ] Navigate to your local libraries `.venv/Lib` folder and check that dbt is installed (one of folders is named `dbt`) - as shown in snip 2. Please take a snip of your `.venv/Lib` folder as shown in snip 2.

[Instructions on how to attach snips/images](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)

### Snip 1 (check python configuration)

![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/45013044/afc1fd2c-819a-465a-beb8-3fcd8599a3e9)


### Snip 2 (Check DBT installation)

![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/45013044/cc6e95f4-eceb-414b-8e21-ffd6eb6241da)

**Comment by Nat325** [comment]
Notes from going through above steps:

- not able to discard changes since no changes were made (step 1)
- When creating a new branch it prompts me to either leave my changes on main or bring them to the new branch, which one should I choose? @ran-codes  (step 3)

![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/116823103/c80777ab-e602-4288-ac65-6ca5e81fe9aa)

**Comment by ran-codes** [comment]
@Nat325 i made some changes  please pull  ([instructions on pulling](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/keeping-your-local-repository-in-sync-with-github/syncing-your-branch-in-github-desktop#pulling-to-your-local-branch-from-the-remote)). This should clear up your index and allow you to proceed.

Please let me know if you still have changes

**Comment by Nat325** [comment]
step 4 - are those the correct instructions for publishing the branch to origin? It links me to the discarding changes section

**Comment by ran-codes** [comment]
sorry about that. Fixed the link! (give it another try)! THanks!

**Comment by Nat325** [comment]
![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/116823103/bea0f350-b354-4d14-b07d-ca02262c6436)
So I believe I followed all of the steps correctly before snip 1, but I can't find the .venv folder to get the snippet you are requesting

**Comment by ran-codes** [comment]
fanstatic! glad we fixed the first problem.


minor thing @Nat325  I don't think you published your branch (I can't see it on GitHub). can you 

- upload a snip of your github desktop
- make sure you are on your own branch and try pushing again **[instructions on how to publish branch to origin](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/making-changes-in-a-branch/managing-branches-in-github-desktop#publishing-a-branch))**

**Comment by Nat325** [comment]
![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/116823103/c0bb47f0-45e7-4072-912c-333d0d83daab)
So that's another thing I wasn't sure of, I did follow the steps above but I may not have published my branch correctly? Github desktop says that natalie-dbt has already been published

**Comment by ran-codes** [comment]
You did it correctly! But I didn't give you collaborator rights so it didn't go through the main repository (my bad 😢).


Can you delete your repository and clone again (starting from [step 1.6](https://drexel-uhc.github.io/analytics-corner/pages/manuals/dbt/get-started-install.html#clone-template-repository-duckdb-dbt-template)). Then create a branch nd publish... this time it should work because I I made you a collaborator on the correct GitHub repo we are working on. 

(this is good GitHub practice -  you'll be a pro in no time 👍 )

**Comment by Nat325** [comment]
![image](https://github.com/Drexel-UHC/duckdb-dbt-template/assets/116823103/dc0dc330-1b28-41e1-b67c-e070b70e7594)
I did it! Looks like all is well now. Thanks Ran!

**Comment by ran-codes** [comment]
great job @Nat325 🍰
